set(CMAKE_SYSTEM_NAME Linux)
set(CMAKE_SYSTEM_PROCESSOR aarch64)

# Yocto SDK cross-compiler (source environment-setup-aarch64-poky-linux first)
set(CMAKE_C_COMPILER   $ENV{CC}  CACHE STRING "" FORCE)
set(CMAKE_CXX_COMPILER $ENV{CXX} CACHE STRING "" FORCE)
set(CMAKE_SYSROOT      $ENV{SDKTARGETSYSROOT} CACHE STRING "" FORCE)

set(CMAKE_FIND_ROOT_PATH_MODE_PROGRAM NEVER)
set(CMAKE_FIND_ROOT_PATH_MODE_LIBRARY ONLY)
set(CMAKE_FIND_ROOT_PATH_MODE_INCLUDE ONLY)
