// Force-enable asserts even under Release builds.
#ifdef NDEBUG
#  undef NDEBUG
#endif

// IndicMioIstft vs the upstream torch "same"-padding ISTFT: the fixture under
// tests/data was generated by miocodec's ISTFT on a seeded random spectrum
// (see speech-models hindi-emotion-tts export notes). Bit-level agreement is
// not expected across FFT implementations; the gate is tight elementwise and
// RMS tolerances, which catch scaling, window, overlap-add, and trim bugs.

#include "../src/models/litert/indic_mio_istft.h"

#include <cassert>
#include <cmath>
#include <cstdio>
#include <fstream>
#include <string>
#include <vector>

namespace {

std::vector<float> read_f32(const std::string& path) {
    std::ifstream f(path, std::ios::binary);
    assert(f && "fixture missing");
    f.seekg(0, std::ios::end);
    const std::streamoff n = f.tellg();
    f.seekg(0);
    std::vector<float> out(static_cast<size_t>(n) / sizeof(float));
    f.read(reinterpret_cast<char*>(out.data()), n);
    return out;
}

}  // namespace

int main() {
    const std::string dir = std::string(SPEECH_CORE_TEST_DATA_DIR);
    const auto real = read_f32(dir + "/indic_mio_istft_real.bin");
    const auto imag = read_f32(dir + "/indic_mio_istft_imag.bin");
    const auto want = read_f32(dir + "/indic_mio_istft_pcm.bin");

    constexpr int kFrames = 8, kNfft = 1920, kHop = 480;
    constexpr int kBins = kNfft / 2 + 1;
    assert(real.size() == static_cast<size_t>(kBins) * kFrames);
    assert(imag.size() == real.size());

    speech_core::IndicMioIstft istft(kNfft, kHop);
    const auto got = istft.synthesize(real.data(), imag.data(), kFrames);

    assert(got.size() == want.size());

    double err_sq = 0.0, ref_sq = 0.0;
    float max_abs_err = 0.0f;
    for (size_t i = 0; i < got.size(); ++i) {
        const float d = got[i] - want[i];
        max_abs_err = std::max(max_abs_err, std::fabs(d));
        err_sq += static_cast<double>(d) * d;
        ref_sq += static_cast<double>(want[i]) * want[i];
    }
    const double rel_rms = std::sqrt(err_sq / ref_sq);
    std::printf("istft: n=%zu max|err|=%.3e rel_rms=%.3e\n",
                got.size(), max_abs_err, rel_rms);
    assert(max_abs_err < 1e-4f);
    assert(rel_rms < 1e-5);

    // Degenerate shapes stay well-formed.
    const auto one = istft.synthesize(real.data(), imag.data(), 1);
    assert(one.size() == static_cast<size_t>(kNfft - (kNfft - kHop)));
    std::printf("istft: PASS\n");
    return 0;
}
