// Pins mel_spectrogram's Parakeet/NeMo training-contract mode to the Python
// reference feature extractor (transformers ParakeetFeatureExtractor):
// torch.stft(center=True, pad_mode="constant"), hann(win, periodic=False)
// centered in the n_fft frame, Slaney filterbank, log(x + 2^-24).
//
// Expectations were generated by the element-wise-verified NumPy replica of
// the reference extractor (matches it to float32 noise on real audio; the
// 2026-07-18 same-items bench showed the previous off-contract front-end
// cost +0.40..+1.00 WER per European slice in production). Tolerance covers
// float32 FFT/filterbank rounding between implementations. The input is an
// analytic three-tone signal so the test needs no fixture files.

#include "speech_core/audio/mel.h"

#include <cmath>
#include <cstdio>
#include <vector>

int main() {
    constexpr int kSr = 16000, kNfft = 512, kHop = 160, kWin = 400;
    constexpr int kMels = 128;
    constexpr size_t kLen = 8000;
    constexpr float kPi = 3.14159265358979323846f;

    std::vector<float> sig(kLen);
    for (size_t i = 0; i < kLen; ++i) {
        const float t = static_cast<float>(i);
        sig[i] = 0.3f * std::sin(2.0f * kPi * 440.0f * t / kSr)
               + 0.2f * std::sin(2.0f * kPi * 1873.0f * t / kSr)
               + 0.1f * std::sin(2.0f * kPi * 7000.5f * t / kSr);
    }

    // Pre-emphasis exactly as ParakeetStt::compute_mel applies it.
    std::vector<float> emphasized(kLen);
    emphasized[0] = sig[0];
    for (size_t i = 1; i < kLen; ++i) {
        emphasized[i] = sig[i] - 0.97f * sig[i - 1];
    }

    auto mel = speech_core::audio::mel_spectrogram(
        emphasized.data(), emphasized.size(), kSr, kNfft, kHop, kWin, kMels,
        /*slaney_norm=*/true, /*log_floor=*/5.960464478e-8f,
        /*center=*/true, /*torch_stft_layout=*/true,
        /*center_pad_zeros=*/true, /*symmetric_torch_window=*/true);

    const int frames = static_cast<int>(mel.size()) / kMels;
    if (frames != 51) {
        std::printf("FAIL: expected 51 frames (torch layout, len/hop+1), "
                    "got %d\n", frames);
        return 1;
    }

    struct Probe { int bin; int frame; float expect; };
    // Generated by the verified reference replica; see file header.
    const Probe probes[] = {
        {0, 0, -8.996833f},   {0, 10, -16.505960f},
        {0, 25, -16.504980f}, {0, 50, -9.211312f},
        {31, 0, -6.711732f},  {31, 10, -14.833428f},
        {31, 25, -14.832205f},{31, 50, -5.369891f},
        {64, 0, -3.410691f},  {64, 10, -9.869390f},
        {64, 25, -9.869204f}, {64, 50, -3.188155f},
        {127, 0, -4.401032f}, {127, 10, -16.447432f},
        {127, 25, -16.512592f},{127, 50, -6.727474f},
    };

    int failures = 0;
    for (const auto& p : probes) {
        const float got = mel[p.bin * frames + p.frame];
        const float diff = std::fabs(got - p.expect);
        // 2e-2 covers float32 FFT-implementation noise on probes with real
        // energy. Probes at the additive floor (log(2^-24) = -16.6) measure
        // pure spectral leakage at ~1e-8 magnitude, where float32-vs-float64
        // FFT differences legitimately move the log by a few tenths — there
        // the probe only asserts the floor regime. The failure modes this
        // test exists for (wrong pad mode, window, layout, bank) are >1.0.
        const float tol = (p.expect < -15.5f) ? 0.5f : 2e-2f;
        if (diff > tol) {
            std::printf("FAIL: bin=%d frame=%d expect=%.6f got=%.6f "
                        "(diff %.2e)\n", p.bin, p.frame, p.expect, got, diff);
            ++failures;
        }
    }

    if (failures == 0) {
        std::printf("test_mel_parakeet_contract: 16/16 probes match the reference "
                    "extractor (2e-2 energy probes, 0.5 floor probes)\n");
        return 0;
    }
    return 1;
}
