// Chatterbox T3 LiteRT loop verification driver.
//
// Proves the deployment-complete T3 graphs (t3_prefill_v2 + t3_step_v2) reproduce
// the PyTorch reference under GREEDY decoding: prefill(text_ids, cond_emb) -> KV
// cache, then a greedy AR step loop -> speech tokens, compared against golden
// tokens generated by gen_golden.py.
//
//   chatterbox_t3_check <bundle_dir> <golden.json>
//
// ai-edge-torch scrambles graph input/output order, so we map every tensor by
// parsing the "args_N" / "output_N" index out of its signature name.

#include "speech_core/models/litert_engine.h"

#include <litert/c/litert_model.h>

#include <cstdint>
#include <cstdio>
#include <cstring>
#include <fstream>
#include <regex>
#include <sstream>
#include <string>
#include <vector>

using namespace speech_core;

namespace {

constexpr int D = 1024, L = 30, NKV = 16, HD = 64;
constexpr int VOCAB = 8194;
constexpr int PREFILL_T = 512, TEXT_PAD = 478, COND_LEN = 34;
constexpr int STEP_CACHE = 1536;
constexpr int BOS = 6561, STOP = 6562;

std::vector<char> read_file(const std::string& p) {
    std::ifstream f(p, std::ios::binary | std::ios::ate);
    if (!f) throw std::runtime_error("cannot open " + p);
    std::streamsize n = f.tellg(); f.seekg(0);
    std::vector<char> b(static_cast<size_t>(n));
    f.read(b.data(), n);
    return b;
}

// Pull the integer list following "\"key\": [" out of a JSON blob.
std::vector<long> json_int_array(const std::string& s, const std::string& key) {
    size_t k = s.find("\"" + key + "\"");
    if (k == std::string::npos) throw std::runtime_error("key not found: " + key);
    size_t lb = s.find('[', k), rb = s.find(']', lb);
    std::string body = s.substr(lb + 1, rb - lb - 1);
    std::vector<long> out;
    std::stringstream ss(body); std::string tok;
    while (std::getline(ss, tok, ',')) {
        // trim
        size_t a = tok.find_first_not_of(" \t\r\n");
        if (a == std::string::npos) continue;
        out.push_back(std::stol(tok.substr(a)));
    }
    return out;
}

int parse_idx(const std::string& name, const std::string& tag) {
    std::smatch m;
    std::regex re(tag + R"(_(\d+))");
    if (std::regex_search(name, m, re)) return std::stoi(m[1]);
    throw std::runtime_error("no " + tag + "_N in " + name);
}

// A loaded graph + its signature name->index maps.
struct Graph {
    LiteRtModel model = nullptr;
    LiteRtCompiledModel compiled = nullptr;
    LiteRtSignature sig = nullptr;
    std::vector<int> in_logical;   // in_logical[sig_input_index]  = logical arg N
    std::vector<int> out_logical;  // out_logical[sig_output_index] = logical output M

    void load(const std::string& path) {
        LiteRTEngine::get().load(path, false, &model, &compiled);
        litert_check(LiteRtGetModelSignature(model, 0, &sig), "GetModelSignature");
        LiteRtParamIndex nin = 0, nout = 0;
        litert_check(LiteRtGetNumSignatureInputs(sig, &nin), "NumSigInputs");
        litert_check(LiteRtGetNumSignatureOutputs(sig, &nout), "NumSigOutputs");
        in_logical.resize(nin); out_logical.resize(nout);
        for (LiteRtParamIndex i = 0; i < nin; ++i) {
            const char* nm = nullptr;
            litert_check(LiteRtGetSignatureInputName(sig, i, &nm), "SigInputName");
            in_logical[i] = parse_idx(nm, "args");
        }
        for (LiteRtParamIndex i = 0; i < nout; ++i) {
            const char* nm = nullptr;
            litert_check(LiteRtGetSignatureOutputName(sig, i, &nm), "SigOutputName");
            out_logical[i] = parse_idx(nm, "output");
        }
    }
};

float argmax(const std::vector<float>& v, int& idx) {
    idx = 0; float best = v[0];
    for (int i = 1; i < (int)v.size(); ++i) if (v[i] > best) { best = v[i]; idx = i; }
    return best;
}

}  // namespace

int main(int argc, char** argv) {
    if (argc < 3) { std::fprintf(stderr, "usage: %s <bundle_dir> <golden.json>\n", argv[0]); return 2; }
    std::string dir = argv[1], golden = argv[2];
    LiteRtEnvironment env = LiteRTEngine::get().env();

    // --- golden ---
    std::string gj(read_file(golden).data(), read_file(golden).size());
    auto text_ids_l = json_int_array(gj, "text_token_ids");
    auto golden_sp  = json_int_array(gj, "speech_tokens");
    const int prefix_len = COND_LEN + (int)text_ids_l.size();
    std::printf("golden: text_ids=%zu speech_tokens=%zu prefix_len=%d\n",
                text_ids_l.size(), golden_sp.size(), prefix_len);

    // --- cond_emb.bin (float32 [1,34,1024]) ---
    auto cb = read_file(dir + "/cond_emb.bin");
    std::vector<float> cond_emb(COND_LEN * D);
    std::memcpy(cond_emb.data(), cb.data(), cond_emb.size() * sizeof(float));

    // Optional explicit graph paths (argv[3]=prefill, argv[4]=step) to test fp32
    // graphs while cond_emb.bin + golden come from the bundle dir.
    std::string prefill_path = argc >= 4 ? argv[3] : (dir + "/chatterbox-t3-prefill.tflite");
    std::string step_path    = argc >= 5 ? argv[4] : (dir + "/chatterbox-t3-step.tflite");
    Graph prefill, step;
    prefill.load(prefill_path);
    step.load(step_path);

    // ---------- PREFILL ----------
    std::vector<int64_t> text_ids(TEXT_PAD, 0);
    for (size_t i = 0; i < text_ids_l.size(); ++i) text_ids[i] = text_ids_l[i];

    // Per-layer caches (host side), grown to STEP_CACHE for the step loop.
    std::vector<std::vector<float>> K(L), V(L);
    for (int l = 0; l < L; ++l) { K[l].assign(NKV * STEP_CACHE * HD, 0.f); V[l].assign(NKV * STEP_CACHE * HD, 0.f); }
    {
        auto t_ids  = make_type(kLiteRtElementTypeInt64,   {1, TEXT_PAD});
        auto t_cond = make_type(kLiteRtElementTypeFloat32, {1, COND_LEN, D});
        auto t_log  = make_type(kLiteRtElementTypeFloat32, {1, PREFILL_T, VOCAB});
        auto t_kv   = make_type(kLiteRtElementTypeFloat32, {1, NKV, PREFILL_T, HD});

        LiteRtHostBuffer in_ids (env, t_ids,  text_ids.size() * sizeof(int64_t), text_ids.data());
        LiteRtHostBuffer in_cond(env, t_cond, cond_emb.size() * sizeof(float),   cond_emb.data());
        LiteRtHostBuffer out_log(env, t_log,  (size_t)PREFILL_T * VOCAB * sizeof(float));
        std::vector<LiteRtHostBuffer> kbuf, vbuf;
        kbuf.reserve(L); vbuf.reserve(L);
        for (int l = 0; l < L; ++l) { kbuf.emplace_back(env, t_kv, (size_t)NKV * PREFILL_T * HD * sizeof(float)); }
        for (int l = 0; l < L; ++l) { vbuf.emplace_back(env, t_kv, (size_t)NKV * PREFILL_T * HD * sizeof(float)); }

        // logical inputs: 0=text_ids, 1=cond_emb
        std::vector<LiteRtTensorBuffer> ins(prefill.in_logical.size());
        for (size_t i = 0; i < prefill.in_logical.size(); ++i)
            ins[i] = (prefill.in_logical[i] == 0 ? in_ids.raw() : in_cond.raw());
        // logical outputs: 0=logits, 1..L=K, L+1..2L=V
        std::vector<LiteRtTensorBuffer> outs(prefill.out_logical.size());
        for (size_t j = 0; j < prefill.out_logical.size(); ++j) {
            int m = prefill.out_logical[j];
            outs[j] = m == 0 ? out_log.raw() : (m <= L ? kbuf[m - 1].raw() : vbuf[m - 1 - L].raw());
        }
        litert_check(LiteRtRunCompiledModel(prefill.compiled, 0, ins.size(), ins.data(),
                                            outs.size(), outs.data()), "prefill Run");
        // copy first prefix_len cache positions into the step-sized buffers
        std::vector<float> tmp(NKV * PREFILL_T * HD);
        for (int l = 0; l < L; ++l) {
            kbuf[l].read(tmp.data(), tmp.size() * sizeof(float));
            for (int h = 0; h < NKV; ++h)
                std::memcpy(&K[l][h * STEP_CACHE * HD], &tmp[h * PREFILL_T * HD], prefix_len * HD * sizeof(float));
            vbuf[l].read(tmp.data(), tmp.size() * sizeof(float));
            for (int h = 0; h < NKV; ++h)
                std::memcpy(&V[l][h * STEP_CACHE * HD], &tmp[h * PREFILL_T * HD], prefix_len * HD * sizeof(float));
        }
    }

    // ---------- GREEDY AR LOOP ----------
    auto t_scalar1 = make_type(kLiteRtElementTypeInt64, {1, 1});
    auto t_pos     = make_type(kLiteRtElementTypeInt64, {1});
    auto t_log1    = make_type(kLiteRtElementTypeFloat32, {1, 1, VOCAB});
    auto t_kv      = make_type(kLiteRtElementTypeFloat32, {1, NKV, STEP_CACHE, HD});
    const int max_steps = (int)golden_sp.size() + 4;
    std::vector<long> gen;
    int tok = BOS;
    std::vector<float> logits(VOCAB);
    for (int s = 0; s < max_steps; ++s) {
        int64_t tok64 = tok, spos = s, cpos = prefix_len + s;
        LiteRtHostBuffer in_tok (env, t_scalar1, sizeof(int64_t), &tok64);
        LiteRtHostBuffer in_spos(env, t_scalar1, sizeof(int64_t), &spos);
        LiteRtHostBuffer in_cpos(env, t_pos,     sizeof(int64_t), &cpos);
        std::vector<LiteRtHostBuffer> inK, inV, outK, outV;
        inK.reserve(L); inV.reserve(L); outK.reserve(L); outV.reserve(L);
        const size_t kvbytes = (size_t)NKV * STEP_CACHE * HD * sizeof(float);
        for (int l = 0; l < L; ++l) inK.emplace_back(env, t_kv, kvbytes, K[l].data());
        for (int l = 0; l < L; ++l) inV.emplace_back(env, t_kv, kvbytes, V[l].data());
        for (int l = 0; l < L; ++l) outK.emplace_back(env, t_kv, kvbytes);
        for (int l = 0; l < L; ++l) outV.emplace_back(env, t_kv, kvbytes);
        LiteRtHostBuffer out_log(env, t_log1, VOCAB * sizeof(float));

        // logical inputs: 0=tok,1=spos,2=cpos,3..L+2=K,L+3..2L+2=V
        std::vector<LiteRtTensorBuffer> ins(step.in_logical.size());
        for (size_t i = 0; i < step.in_logical.size(); ++i) {
            int n = step.in_logical[i];
            ins[i] = n == 0 ? in_tok.raw() : n == 1 ? in_spos.raw() : n == 2 ? in_cpos.raw()
                     : (n - 3 < L ? inK[n - 3].raw() : inV[n - 3 - L].raw());
        }
        // logical outputs: 0=logits, 1..L=K, L+1..2L=V
        std::vector<LiteRtTensorBuffer> outs(step.out_logical.size());
        for (size_t j = 0; j < step.out_logical.size(); ++j) {
            int m = step.out_logical[j];
            outs[j] = m == 0 ? out_log.raw() : (m <= L ? outK[m - 1].raw() : outV[m - 1 - L].raw());
        }
        litert_check(LiteRtRunCompiledModel(step.compiled, 0, ins.size(), ins.data(),
                                            outs.size(), outs.data()), "step Run");
        out_log.read(logits.data(), logits.size() * sizeof(float));
        int nxt; argmax(logits, nxt);
        if (nxt == STOP) break;
        gen.push_back(nxt);
        for (int l = 0; l < L; ++l) { outK[l].read(K[l].data(), kvbytes); outV[l].read(V[l].data(), kvbytes); }
        tok = nxt;
    }

    // ---------- COMPARE ----------
    int match = 0; int n = (int)std::min(gen.size(), golden_sp.size());
    for (int i = 0; i < n; ++i) if (gen[i] == golden_sp[i]) ++match;
    std::printf("generated=%zu golden=%zu  first-%d match=%d (%.1f%%)\n",
                gen.size(), golden_sp.size(), n, match, n ? 100.0 * match / n : 0.0);
    bool ok = gen.size() == golden_sp.size() && match == n;
    std::printf(ok ? "T3-LOOP-PASS\n" : "T3-LOOP-MISMATCH\n");
    return ok ? 0 : 1;
}
